version: "3.7"


services:
  mongo:
    image: mongo:6.0-jammy@sha256:aefae4865d1a803f4ffc543bc9b26694025c4faa3517b6dc45c4065e89b6cc7c
    ports:
      - published: 27017
        target: 27017

  uwsgi:
    image: jnorwood/stupidchess-uwsgi:2023.8.1
    environment:
      JCONFIGURE_ACTIVE_PROFILES: LCL
      JCONFIGURE_CONFIG_DIRECTORIES: /etc/stupidchess/config
    volumes:
      - type: volume
        source: stupidchess-sockets
        target: /run/stupidchess

  nginx:
    image: jnorwood/stupidchess-nginx:current
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/stupidchess/nginx.conf
        read_only: true
      - type: volume
        source: frontend-public-volume
        target: /etc/stupidchess/dist
        read_only: true
      - type: volume
        source: stupidchess-sockets
        target: /run/stupidchess
      - type: volume
        source: stupidchess-nginx-runtime
        target: /run/stupidchess-nginx

  socat:
    image: jnorwood/stupidchess-socat:current
    build:
      context: docker
      dockerfile: Dockerfile-socat
    ports:
      - published: 23180
        target: 23080
    volumes:
      - type: volume
        source: stupidchess-nginx-runtime
        target: /run/stupidchess-nginx

  webpack_builder:
    image: jnorwood/stupidchess-webpack_builder:current
    build:
      context: .
      dockerfile: docker/Dockerfile-webpack_builder
    entrypoint:
      - node_modules/webpack/bin/webpack.js
      - --watch
      - --devtool
      - source-map
    volumes:
      - type: bind
        source: ./src
        target: /etc/stupidchess/src
        read_only: true
      - type: volume
        source: frontend-public-volume
        target: /etc/stupidchess/dist

volumes:
  frontend-public-volume:
  stupidchess-nginx-runtime:
  stupidchess-sockets:
