version: "3.7"

volumes:
  socket-volume:
  frontend-public-volume:

services:
  mongo:
    image: mongo:2.6.4
    ports:
      - published: 27017
        target: 27017

  nginx:
    image: jnorwood/stupidchess-nginx:current
    build:
      context: .
      dockerfile: docker/Dockerfile-nginx
    entrypoint:
      - nginx
      - -c
      - /opt/stupidchess/nginx.conf
      - -g
      - daemon off;
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /opt/stupidchess/nginx.conf
        read_only: true
      - type: volume
        source: frontend-public-volume
        target: /opt/stupidchess/dist
        read_only: true
      - type: volume
        source: socket-volume
        target: /opt/stupidchess/sockets
    ports:
      - published: 80
        target: 23080

  uwsgi:
    image: jnorwood/stupidchess-uwsgi:19.1205.0
    environment:
      JCONFIGURE_ACTIVE_PROFILES: LCL
      JCONFIGURE_CONFIG_DIRECTORIES: /opt/stupidchess/config
    volumes:
      - type: volume
        source: socket-volume
        target: /opt/stupidchess/sockets

  webpack_builder:
    image: jnorwood/stupidchess-webpack_builder:current
    build:
      context: .
      dockerfile: docker/Dockerfile-webpack_builder
    entrypoint:
      - node_modules/webpack/bin/webpack.js
      - --watch
      - --devtool
      - source-map
    volumes:
      - type: bind
        source: ./src
        target: /opt/stupidchess/src
        read_only: true
      - type: volume
        source: frontend-public-volume
        target: /opt/stupidchess/dist
