FROM node:10.15-alpine
LABEL maintainer=norwood.john.m@gmail.com

WORKDIR /opt/stupidchess
COPY package.json .
RUN npm install

COPY .babelrc .
COPY .eslintrc .
COPY webpack.config.js .

ENTRYPOINT ["node_modules/webpack/bin/webpack.js", "-p", "--progress"]
