##
# This stage of the build installs webpack and npm, and then builds a public dist archive out of our frontend code
##
FROM node:8.11.1-slim AS artifacts
LABEL maintainer=norwood.john.m@gmail.com

ARG APP_DIR=/opt/stupidchess
WORKDIR ${APP_DIR}

COPY package.json .
RUN npm install

COPY .babelrc .
COPY .eslintrc .
COPY webpack.config.js .
COPY src ./src

RUN node_modules/webpack/bin/webpack.js -p --progress


##
# This stage copies the generated dist archive from the previous stage of the build into the application home, and adds the
# nginx config file
##
FROM nginx:1.13.12
LABEL maintainer=norwood.john.m@gmail.com

ARG APP_DIR=/opt/stupidchess
WORKDIR ${APP_DIR}

COPY --from=artifacts ${APP_DIR}/dist ./dist
COPY etc/nginx/nginx.conf /etc/nginx/nginx.conf
