FROM node:18-bookworm@sha256:a52ed7aa0ea502c2e06a1066c80a8adf4163d4edc47ee3257e573cd55a7828b0
LABEL maintainer=norwood.john.m@gmail.com

WORKDIR /etc/stupidchess
COPY package.json .
RUN npm install

COPY .babelrc .
COPY .eslintrc .
COPY webpack.config.js .

ENTRYPOINT ["node_modules/webpack/bin/webpack.js", "-p", "--progress"]
