##
# This stage of the build installs webpack and npm, and then builds a public dist archive out of our frontend code
##
FROM node:18-bookworm@sha256:a52ed7aa0ea502c2e06a1066c80a8adf4163d4edc47ee3257e573cd55a7828b0 AS artifacts
LABEL maintainer=norwood.john.m@gmail.com

ARG APP_DIR=/etc/stupidchess
WORKDIR ${APP_DIR}

COPY package.json .
RUN npm install

COPY .babelrc .
COPY .eslintrc .
COPY webpack.config.js .
COPY src ./src

RUN node_modules/webpack/bin/webpack.js -p --progress


##
# This stage copies the generated dist archive from the previous stage of the build into the application home, and adds the
# nginx config file
##
FROM nginx:1.25.1-bookworm@sha256:d2b2f2980e9ccc570e5726b56b54580f23a018b7b7314c9eaff7e5e479c78657
LABEL maintainer=norwood.john.m@gmail.com

ARG APP_DIR=/etc/stupidchess
ARG LOG_DIR=/var/log/stupidchess
ARG RUNTIME_DIR=/run/stupidchess-nginx
ARG USER=stupidchess

WORKDIR ${APP_DIR}

RUN mkdir -p ${LOG_DIR} \
    && mkdir -p ${RUNTIME_DIR} \
    && ln -s /dev/stdout ${LOG_DIR}/nginx-access.log \
    && ln -s /dev/stderr ${LOG_DIR}/nginx-errors.log

COPY --from=artifacts ${APP_DIR}/dist ./dist
COPY nginx.conf ${APP_DIR}/nginx.conf

ENTRYPOINT ["nginx", "-c", "/etc/stupidchess/nginx.conf", "-g", "daemon off; user root;"]
