##
# This stage of the build installs webpack and npm, and then builds a public dist archive out of our frontend code
##
FROM node:18-bookworm@sha256:a52ed7aa0ea502c2e06a1066c80a8adf4163d4edc47ee3257e573cd55a7828b0 AS artifacts
LABEL maintainer=norwood.john.m@gmail.com

ARG APP_DIR=/etc/stupidchess
WORKDIR ${APP_DIR}

COPY package.json package-lock.json .
RUN npm install

COPY .babelrc .
COPY .eslintrc .
COPY webpack.config.js .
COPY src ./src

RUN node_modules/webpack/bin/webpack.js -p --progress


##
# This stage copies the generated dist archive from the previous stage of the build into the application home, and adds the
# nginx config file
##
FROM nginx:1.25.1-bookworm@sha256:d2b2f2980e9ccc570e5726b56b54580f23a018b7b7314c9eaff7e5e479c78657
LABEL maintainer=norwood.john.m@gmail.com

ARG APP_DIR=/etc/stupidchess
ARG RUNTIME_DIR=/run/stupidchess-nginx

WORKDIR ${APP_DIR}

RUN mkdir -p ${RUNTIME_DIR}

COPY --from=artifacts ${APP_DIR}/dist ./dist
COPY nginx.conf ${APP_DIR}/nginx.conf

ENTRYPOINT ["bash", "-c", "ln -s /run/systemd/journal/dev-log /dev/log && nginx -c /etc/stupidchess/nginx.conf -g 'daemon off; user root;'"]
